//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTable
    {
        public int AnswerId { get; set; }
        public string AnswerDesc { get; set; }
        public int QuestionId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> LangId { get; set; }
    
        public virtual LangTable LangTable { get; set; }
        public virtual QuestionTable QuestionTable { get; set; }
        public virtual UserRegisteration UserRegisteration { get; set; }
    }
}
