//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileTable
    {
        public int UserId { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string City { get; set; }
        public string About { get; set; }
        public string Qualification { get; set; }
        public string Designation { get; set; }
    
        public virtual UserRegisteration UserRegisteration { get; set; }
    }
}
